---
title: "Yahoo Finance stock price analysis"
author: "Grzegorz Chadysz, Konrad Archiciński"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: yes
  html_document:
    toc: yes
params:
  Company:
    value: "MSFT"
    input: select
    choices: ["INTC", "MSFT", "NVDA", "AMD", "GM", "F", "TM"]
  From: 
    value: !r lubridate::today() - 1000
    input: date
    max: !r lubridate::today()
  To:
    value: !r lubridate::today()
    input: date
    max: !r lubridate::today()
  Columns: 
    value: "None"
    label: "Quotes (remove with DEL)"
    choices: ["Open", "High", "Low", "Close", "Volume", "Adjusted"]
    input: select
    multiple: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F, message=F, warning=F}
library(quantmod)
library(tidyverse)
library(data.table)
library(kableExtra)
library(hrbrthemes)
library(plotly)
library(urca)
```

## Intro

Checking parameters:

```{r}
print(params$Company)
print(params$From)
print(params$To)
print(params$Columns)
```

## Data

Getting the quotes:

```{r, echo=F, message=F, warning=F}
quotes <- getSymbols(
  params$Company,
  auto.assign = F,
  from = params$From,
  to = params$To
)
```

Displaying selected columns:

```{r, echo=F, warning=F}
columns_all <- c("Open", "High", "Low", "Close", "Volume", "Adjusted")

# If no columns were selected then all are selected by default
if (params$Columns == "None"){
  columns_to_keep <- paste0(params$Company, ".", columns_all)
} else {
  columns_to_keep <- paste0(params$Company, ".", params$Columns)
}

# Subsetting selected columns
quotes <- subset(quotes, select = columns_to_keep)

# Changing to data frame format
quotes <- data.frame(Date = index(quotes), coredata(quotes))

kable(tail(quotes), row.names = F, caption = "Preview of the data") %>%
  kable_styling(bootstrap_options = c("striped"))
```

## Plot

```{r, echo=F, warning=F, message=F}
# Melting the data into long format in order to plot more efficiently
quotes_long <- melt(quotes, id = "Date")
```

### Ggplot

```{r, echo=F, out.width="100%"}
ggplot(quotes_long, aes(x = Date)) +
  geom_line(aes(y = value)) +
  theme_modern_rc() +
  facet_wrap(~variable, scales = "free") +
  theme(strip.text = element_text(color = "white")) 
```

### Plotly

```{r, echo=F, out.width="100%", warning=F}
p <- ggplot(quotes_long, aes(x = Date)) +
  geom_line(aes(y = value)) +
  theme_modern_rc() +
  facet_wrap(~variable, scales = "free") +
  theme(strip.text = element_text(color = "white")) 

ggplotly(p)
```

## Stationarity analysis

```{r, eval=T}
# First column is to be tested for stationarity
series_to_test <- xts(x = quotes[[2]], order.by = quotes[[1]])
test_statistic = 1
critical_value = 0
i = -1

while(test_statistic >= critical_value){
  test <- ur.df(series_to_test, type = "none")
  test_statistic <- test@teststat[1] 
  critical_value <- test@cval[1, 2]
  series_to_test <- diff.xts(series_to_test, na.pad = F)
  i = i + 1   # counter for differentiating order
}
# ADF test summary
summary(test)

# Stationary plot
ggplot(series_to_test, aes(x = index(series_to_test), y = coredata(series_to_test))) +
  geom_line() +
  theme_modern_rc() +
  labs(x = "Date", y = "Value")
```



